Update for soybase.org/sequenceserver

diff --git a/db/Dockerfile b/db/Dockerfile
--- a/db/Dockerfile
+++ b/db/Dockerfile
@@ -4,66 +4,36 @@ WORKDIR /db
 VOLUME ["/db"]
 
 ENV DATA_STORE=https://v1.legumefederation.org/data/public
-RUN printf '#!/bin/bash\nset -o pipefail -o errexit -o nounset; curl ${DATA_STORE}/${1} | gzip -dc | makeblastdb -parse_seqids -hash_index -dbtype ${2} -taxid ${3} -title "${4}" -out $(basename ${1#.f*.gz})\n' > /usr/local/bin/mkblastdb \
+RUN printf '%s\n' '#!/bin/bash' 'set -o pipefail -o errexit -o nounset; curl ${DATA_STORE}/${1} | gzip -dc | sed "s/\(gly[a-z][a-z]\.[[:alnum:]]\{1,\}\.gnm[0-9]\{1,\}\.\(ann[0-9]\{1,\}\.\)\{0,1\}\([^[:space:]]*\)\)/\3 dsid=\1/" | makeblastdb -parse_seqids -hash_index -dbtype ${2} -taxid ${3} -title "${4}" -out $(basename ${1#.f*.gz})' > /usr/local/bin/mkblastdb \
   && chmod +x /usr/local/bin/mkblastdb
 
-RUN mkblastdb Arachis_duranensis/V14167.gnm1.ann1.cxSM/aradu.V14167.gnm1.ann1.cxSM.cds.fna.gz nucl 130453 'Arachis duranensis - CDS'
-RUN mkblastdb Arachis_duranensis/V14167.gnm1.ann1.cxSM/aradu.V14167.gnm1.ann1.cxSM.protein.faa.gz prot 130453 'Arachis duranensis - protein'
-RUN mkblastdb Arachis_duranensis/V14167.gnm1.SWBf/aradu.V14167.gnm1.SWBf.genome_main.fna.gz nucl 130453 'Arachis duranensis - genome'
-RUN mkblastdb Arachis_hypogaea/Tifrunner.gnm2.ann1.4K0L/arahy.Tifrunner.gnm2.ann1.4K0L.cds_primaryTranscript.fna.gz nucl 3818 'Arachis hypogaea - CDS'
-RUN mkblastdb Arachis_hypogaea/Tifrunner.gnm2.ann1.4K0L/arahy.Tifrunner.gnm2.ann1.4K0L.protein.faa.gz prot 3818 'Arachis hypogaea - protein'
-RUN mkblastdb Arachis_hypogaea/Tifrunner.gnm2.J5K5/arahy.Tifrunner.gnm2.J5K5.genome_main.fna.gz nucl 3818 'Arachis hypogaea - genome (assembly version 2)'
-RUN mkblastdb Arachis_ipaensis/K30076.gnm1.ann1.J37m/araip.K30076.gnm1.ann1.J37m.cds.fna.gz nucl 130454 'Arachis ipaensis - CDS'
-RUN mkblastdb Arachis_ipaensis/K30076.gnm1.ann1.J37m/araip.K30076.gnm1.ann1.J37m.protein.faa.gz prot 130454 'Arachis ipaensis - protein'
-RUN mkblastdb Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.gnm1.bXJ8.genome_main.fna.gz nucl 130454 'Arachis ipaensis - genome'
-RUN mkblastdb Cajanus_cajan/ICPL87119.gnm1.ann1.Y27M/cajca.ICPL87119.gnm1.ann1.Y27M.cds.fna.gz nucl 3821 'Cajanus cajan - CDS'
-RUN mkblastdb Cajanus_cajan/ICPL87119.gnm1.ann1.Y27M/cajca.ICPL87119.gnm1.ann1.Y27M.protein_main.faa.gz prot 3821 'Cajanus cajan - protein'
-RUN mkblastdb Cajanus_cajan/ICPL87119.gnm1.SBGP/cajca.ICPL87119.gnm1.SBGP.genome_main.fna.gz nucl 3821 'Cajanus cajan - genome'
-RUN mkblastdb Cercis_canadensis/ISC453364.gnm1.ann1.HZJM/cerca.ISC453364.gnm1.B05Z.cds.fna.gz nucl 49801 'Cercis canadensis - CDS'
-RUN mkblastdb Cercis_canadensis/ISC453364.gnm1.B05Z/cerca.ISC453364.gnm1.B05Z.genome_main.fna.gz nucl 49801 'Cercis canadensis - genome'
-RUN mkblastdb Cercis_canadensis/ISC453364.gnm1.ann1.HZJM/cerca.ISC453364.gnm1.B05Z.protein.faa.gz prot 49801 'Cercis canadensis - proteins'
-RUN mkblastdb Cicer_arietinum/ICC4958.gnm2.ann1.LCVX/cicar.ICC4958.gnm2.ann1.LCVX.cds_primaryTranscript.fna.gz nucl 3827 'Cicer arietinum (desi, ICC4958) - CDS'
-RUN mkblastdb Cicer_arietinum/ICC4958.gnm2.ann1.LCVX/cicar.ICC4958.gnm2.ann1.LCVX.protein.faa.gz prot 3827 'Cicer arietinum (desi, ICC4958) - protein'
-RUN mkblastdb Cicer_arietinum/ICC4958.gnm2.bg5m/cicar.ICC4958.gnm2.bg5m.genome_main.fna.gz nucl 3827 'Cicer arietinum (desi, ICC4958) - genome'
-RUN mkblastdb Cicer_arietinum/CDCFrontier.gnm1.ann1.nRhs/cicar.CDCFrontier.gnm1.ann1.nRhs.cds.fna.gz nucl 3827 'Cicer arietinum (kabuli, CDCFrontier) - CDS'
-RUN mkblastdb Cicer_arietinum/CDCFrontier.gnm1.ann1.nRhs/cicar.CDCFrontier.gnm1.ann1.nRhs.protein.faa.gz prot 3827 'Cicer arietinum (kabuli, CDCFrontier) - protein'
-RUN mkblastdb Cicer_arietinum/CDCFrontier.gnm1.GkHc/cicar.CDCFrontier.gnm1.GkHc.genome_main.fna.gz nucl 3827 'Cicer arietinum (kabuli, CDCFrontier) - genome'
-RUN mkblastdb Faidherbia_albida/unk.gnm1.ann1.RTP9/faihe.unk.gnm1.ann1.RTP9.cds.fna.gz nucl 138055 'Faidherbia albida - CDS'
-RUN mkblastdb Faidherbia_albida/unk.gnm1.ZT1R/faial.unk.gnm1.ZT1R.genome_main.fna.gz nucl 138055 'Faidherbia albida - genome'
-RUN mkblastdb Faidherbia_albida/unk.gnm1.ann1.RTP9/faihe.unk.gnm1.ann1.RTP9.protein.faa.gz prot 138055 'Faidherbia albida - proteins'
-RUN mkblastdb Glycine_max/Wm82.gnm2.ann1.RVB6/glyma.Wm82.gnm2.ann1.RVB6.cds.fna.gz nucl 3847 'Glycine max Wm82.a2 - CDS'
-RUN mkblastdb Glycine_max/Wm82.gnm2.DTC4/glyma.Wm82.gnm2.DTC4.genome_main.fna.gz nucl 3847 'Glycine max Wm82.a2 - genome'
-RUN mkblastdb Glycine_max/Wm82.gnm2.ann1.RVB6/glyma.Wm82.gnm2.ann1.RVB6.protein.faa.gz prot 3847 'Glycine max Wm82.a2 - proteins'
-RUN mkblastdb Lotus_japonicus/MG20.gnm3.ann1.WF9B/lotja.MG20.gnm3.ann1.WF9B.cds_primaryTranscript.fna.gz nucl 34305 'Lotus japonicus v3.0 - CDS'
-RUN mkblastdb Lotus_japonicus/MG20.gnm3.QPGB/lotja.MG20.gnm3.QPGB.genome_main.fna.gz nucl 34305 'Lotus japonicus v3.0 - genome'
-RUN mkblastdb Lotus_japonicus/MG20.gnm3.ann1.WF9B/lotja.MG20.gnm3.ann1.WF9B.protein.faa.gz prot 34305 'Lotus japonicus v3.0 - protein'
-RUN mkblastdb Lupinus_albus/Amiga.gnm1.ann0.3GKS/lupal.Amiga.gnm1.ann0.3GKS.cds.fna.gz nucl 3870 'Lupinus albus - CDS'
-RUN mkblastdb Lupinus_albus/Amiga.gnm1.F4NR/lupal.Amiga.gnm1.F4NR.genome_main.fna.gz nucl 3870 'Lupinus albus - genome'
-RUN mkblastdb Lupinus_albus/Amiga.gnm1.ann0.3GKS/lupal.Amiga.gnm1.ann0.3GKS.protein.faa.gz prot 3870 'Lupinus albus - protein'
-RUN mkblastdb Lupinus_angustifolius/Tanjil.gnm1.ann1.nnV9/lupan.Tanjil.gnm1.ann1.nnV9.cds_all.fna.gz nucl 3871 'Lupinus angustifolius - CDS'
-RUN mkblastdb Lupinus_angustifolius/Tanjil.gnm1.Qq0N/lupan.Tanjil.gnm1.Qq0N.genome_main.fna.gz nucl 3871 'Lupinus angustifolius - genome'
-RUN mkblastdb Lupinus_angustifolius/Tanjil.gnm1.ann1.nnV9/lupan.Tanjil.gnm1.ann1.nnV9.protein.faa.gz prot 3871 'Lupinus angustifolius - proteins'
-RUN mkblastdb Medicago_truncatula/A17_HM341.gnm4.ann2.G3ZY/medtr.A17_HM341.gnm4.ann2.G3ZY.cds.fna.gz nucl 3880 'Medicago truncatula v4.0 - CDS'
-RUN mkblastdb Medicago_truncatula/A17_HM341.gnm4.2GZ9/medtr.A17_HM341.gnm4.2GZ9.genome_main.fna.gz nucl 3880 'Medicago truncatula v4.0 - genome'
-RUN mkblastdb Medicago_truncatula/A17_HM341.gnm4.ann2.G3ZY/medtr.A17_HM341.gnm4.ann2.G3ZY.protein.faa.gz prot 3880 'Medicago_truncatula - proteins'
-RUN mkblastdb Phaseolus_lunatus/G27455.gnm1.ann1.JD7C/phalu.G27455.gnm1.ann1.JD7C.cds_primaryTranscript.fna.gz nucl 3884 'Phaseolus lunatus - CDS'
-RUN mkblastdb Phaseolus_lunatus/G27455.gnm1.7NXX/phalu.G27455.gnm1.7NXX.genome_main.fna.gz nucl 3884 'Phaseolus lunatus - genome'
-RUN mkblastdb Phaseolus_lunatus/G27455.gnm1.ann1.JD7C/phalu.G27455.gnm1.ann1.JD7C.protein.faa.gz prot 3884 'Phaseolus lunatus - proteins'
-RUN mkblastdb Phaseolus_vulgaris/G19833.gnm2.ann1.PB8d/phavu.G19833.gnm2.ann1.PB8d.cds_primaryTranscript.fna.gz nucl 3885 'Phaseolus vulgaris v2.1 - CDS'
-RUN mkblastdb Phaseolus_vulgaris/G19833.gnm2.fC0g/phavu.G19833.gnm2.fC0g.genome_main.fna.gz nucl 3885 'Phaseolus vulgaris v2.1 - genome'
-RUN mkblastdb Phaseolus_vulgaris/G19833.gnm2.ann1.PB8d/phavu.G19833.gnm2.ann1.PB8d.protein.faa.gz prot 3885 'Phaseolus vulgaris v2.1 - proteins'
-RUN mkblastdb Pisum_sativum/Cameor.gnm1.ann1.7SZR/pissa.Cameor.gnm1.ann1.7SZR.cds_primaryTranscript.fna.gz nucl 3888 'Pisum sativum - CDS'
-RUN mkblastdb Pisum_sativum/Cameor.gnm1.P4FG/pissa.Cameor.gnm1.P4FG.genome_main.fna.gz nucl 3888 'Pisum sativum - genome'
-RUN mkblastdb Pisum_sativum/Cameor.gnm1.ann1.7SZR/pissa.Cameor.gnm1.ann1.7SZR.protein.faa.gz prot 3888 'Pisum sativum - proteins'
-RUN mkblastdb Trifolium_pratense/MilvusB.gnm2.ann1.DFgp/tripr.MilvusB.gnm2.ann1.DFgp.cds_primaryTranscript.fna.gz nucl 57577 'Trifolium pratense - CDS'
-RUN mkblastdb Trifolium_pratense/MilvusB.gnm2.gNmT/tripr.MilvusB.gnm2.gNmT.genome_main.fna.gz nucl 57577 'Trifolium pratense - genome'
-RUN mkblastdb Trifolium_pratense/MilvusB.gnm2.ann1.DFgp/tripr.MilvusB.gnm2.ann1.DFgp.protein.faa.gz prot 57577 'Trifolium pratense - proteins'
-RUN mkblastdb Vigna_angularis/Gyeongwon.gnm3.ann1.3Nz5/vigan.Gyeongwon.gnm3.ann1.3Nz5.cds_primaryTranscript.fna.gz nucl 3914 'Vigna angularis - CDS'
-RUN mkblastdb Vigna_angularis/Gyeongwon.gnm3.JyYC/vigan.Gyeongwon.gnm3.JyYC.genome_main.fna.gz nucl 3914 'Vigna angularis - genome'
-RUN mkblastdb Vigna_angularis/Gyeongwon.gnm3.ann1.3Nz5/vigan.Gyeongwon.gnm3.ann1.3Nz5.protein.faa.gz prot 3914 'Vigna angularis - proteins'
-RUN mkblastdb Vigna_radiata/VC1973A.gnm6.ann1.M1Qs/vigra.VC1973A.gnm6.ann1.M1Qs.cds.fna.gz nucl 157791 'Vigna radiata - CDS'
-RUN mkblastdb Vigna_radiata/VC1973A.gnm6.3nL8/vigra.VC1973A.gnm6.3nL8.genome_main.fna.gz nucl 157791 'Vigna radiata - genome'
-RUN mkblastdb Vigna_radiata/VC1973A.gnm6.ann1.M1Qs/vigra.VC1973A.gnm6.ann1.M1Qs.protein.faa.gz prot 157791 'Vigna radiata - proteins'
-RUN mkblastdb Vigna_unguiculata/IT97K-499-35.gnm1.ann1.zb5D/vigun.IT97K-499-35.gnm1.ann1.zb5D.cds_primaryTranscript.fna.gz nucl 3917 'Vigna unguiculata - CDS'
-RUN mkblastdb Vigna_unguiculata/IT97K-499-35.gnm1.QnBW/vigun.IT97K-499-35.gnm1.QnBW.genome_main.fna.gz nucl 3917 'Vigna unguiculata - genome'
-RUN mkblastdb Vigna_unguiculata/IT97K-499-35.gnm1.ann1.zb5D/vigun.IT97K-499-35.gnm1.ann1.zb5D.protein.faa.gz prot 3917 'Vigna unguiculata - proteins'
+RUN curl https://ftp.ncbi.nlm.nih.gov/genomes/refseq/plant/Glycine_max/all_assembly_versions/GCF_000004515.5_Glycine_max_v2.1/GCF_000004515.5_Glycine_max_v2.1_assembly_structure/non-nuclear/assembled_chromosomes/FASTA/chrMT.fna.gz | gzip -dc | makeblastdb -parse_seqids -hash_index -dbtype nucl -taxid 3847 -title 'Glycine max mitochondrial genome' -out chrMT
+RUN curl https://ftp.ncbi.nlm.nih.gov/genomes/refseq/plant/Glycine_max/all_assembly_versions/GCF_000004515.5_Glycine_max_v2.1/GCF_000004515.5_Glycine_max_v2.1_assembly_structure/non-nuclear/assembled_chromosomes/FASTA/chrPltd.fna.gz | gzip -dc | makeblastdb -parse_seqids -hash_index -dbtype nucl -taxid 3847 -title 'Glycine max chloroplast genome' -out chrPltd
+RUN curl https://soybase.org/GlycineBlastPages/archives/fn_indels.nt.20140304.fasta.gz | gzip -dc | makeblastdb -hash_index -dbtype nucl -taxid 3847 -title 'Fast Neutron InDels Bolon et al. 2014' -out fn_indels.nt.20140304
+RUN mkblastdb Glycine_max/Wm82.gnm4.ann1.T8TQ/glyma.Wm82.gnm4.ann1.T8TQ.transcript.fna.gz nucl 3847 'Williams 82 Assembly 4 Annotation 1 (Wm82.a4.v1) Transcript Sequences'
+RUN mkblastdb Glycine_max/Wm82.gnm4.ann1.T8TQ/glyma.Wm82.gnm4.ann1.T8TQ.cds.fna.gz nucl 3847 'Williams 82 Assembly 4 Annotation 1 (Wm82.a4.v1) Coding Sequences'
+RUN mkblastdb Glycine_max/Wm82.gnm4.4PTR/glyma.Wm82.gnm4.4PTR.genome_main.fna.gz nucl 3847 'Williams 82 Assembly 4 Genomic Sequence (Wm82.a4)'
+RUN mkblastdb Glycine_max/Wm82.gnm2.DTC4/glyma.Wm82.gnm2.DTC4.genome_main.fna.gz nucl 3847 'Williams 82 Assembly 2 Genomic Sequence (Wm82.a2)'
+RUN mkblastdb Glycine_max/Wm82.gnm2.ann1.RVB6/glyma.Wm82.gnm2.ann1.RVB6.transcript.fna.gz nucl 3847 'Williams 82 Assembly 2 Annotation 1 (Wm82.a2.v1) Transcript Sequences'
+RUN mkblastdb Glycine_max/Wm82.gnm2.ann1.RVB6/glyma.Wm82.gnm2.ann1.RVB6.cds.fna.gz nucl 3847 'Williams 82 Assembly 2 Annotation 1 (Wm82.a2.v1) Coding Sequences'
+RUN mkblastdb Glycine_max/Wm82.gnm1.FCtY/glyma.Wm82.gnm1.FCtY.genome_main.fna.gz nucl 3847 'Williams 82 Assembly 1 Genomic Sequence (Wm82.a1)'
+RUN mkblastdb Glycine_max/Wm82.gnm1.ann1.DvBy/glyma.Wm82.gnm1.ann1.DvBy.cds.fna.gz nucl 3847 'Williams 82 Assembly 1 Annotation 1.1 (Wm82.a1.v1.1)'
+RUN mkblastdb Glycine_max/Wm82.gnm1.ann1.DvBy/glyma.Wm82.gnm1.ann1.DvBy.transcripts.fna.gz nucl 3847 'Williams 82 Assembly 1 Annotation 1.1 (Wm82.a1.v1.1) Transcript Sequences'
+RUN mkblastdb Glycine_max/Wm82.gnm4.ann1.T8TQ/glyma.Wm82.gnm4.ann1.T8TQ.protein.faa.gz prot 3847 'Williams 82 Assembly 4 Annotation 1 (Wm82.a4.v1) Protein Sequences'
+RUN mkblastdb Glycine_max/Wm82.gnm2.ann1.RVB6/glyma.Wm82.gnm2.ann1.RVB6.protein.faa.gz prot 3847 'Williams 82 Assembly 2 Annotation 1 (Wm82.a2.v1) Protein Sequences'
+RUN mkblastdb Glycine_max/Wm82.gnm1.ann1.DvBy/glyma.Wm82.gnm1.ann1.DvBy.protein.faa.gz prot 3847 'Williams 82 Assembly 1 Annotation 1.1 (Wm82.a1.v1.1) Protein Sequences'
+RUN mkblastdb Glycine_max/Lee.gnm1.ann1.6NZV/glyma.Lee.gnm1.ann1.6NZV.cds.fna.gz nucl 3847 'Glycine max cultivar Lee CDS Sequences'
+RUN mkblastdb Glycine_max/Lee.gnm1.ann1.6NZV/glyma.Lee.gnm1.ann1.6NZV.protein.faa.gz prot 3847 'Glycine max cultivar Lee Transcript Protein Sequences'
+RUN mkblastdb Glycine_max/Lee.gnm1.BXNC/glyma.Lee.gnm1.BXNC.genome_main.fna.gz nucl 3847 'Glycine max cultivar Lee Genomic Sequence'
+RUN mkblastdb Glycine_max/Lee.gnm1.ann1.6NZV/glyma.Lee.gnm1.ann1.6NZV.transcript.fna.gz nucl 3847 'Glycine max cultivar Lee Transcript Sequences'
+RUN mkblastdb Glycine_max/Zh13.gnm1.ann1.8VV3/glyma.Zh13.gnm1.ann1.8VV3.cds.fna.gz nucl 3847 'Glycine max cultivar Zhonghuang 13 CDS Sequences'
+RUN mkblastdb Glycine_max/Zh13.gnm1.N6C8/glyma.Zh13.gnm1.N6C8.genome_main.fna.gz nucl 3847 'Glycine max cultivar Zhonghuang 13 Genomic Sequence'
+RUN mkblastdb Glycine_max/Zh13.gnm1.ann1.8VV3/glyma.Zh13.gnm1.ann1.8VV3.protein.faa.gz prot 3847 'Glycine max cultivar Zhonghuang 13 Protein Sequence'
+RUN mkblastdb Glycine_soja/W05.gnm1.ann1.T47J/glyso.W05.gnm1.ann1.T47J.cds.fna.gz nucl 3848 'Glycine soja cultivar W05 CDS sequences'
+RUN mkblastdb Glycine_soja/W05.gnm1.ann1.T47J/glyso.W05.gnm1.ann1.T47J.transcript.fna.gz nucl 3848 'Glycine soja cultivar W05 transcript sequences'
+RUN mkblastdb Glycine_soja/W05.gnm1.SVL1/glyso.W05.gnm1.SVL1.genome_main.fna.gz nucl 3848 'Glycine soja cultivar W05 genomic sequence'
+RUN mkblastdb Glycine_soja/W05.gnm1.ann1.T47J/glyso.W05.gnm1.ann1.T47J.protein.faa.gz prot 3848 'Glycine soja cultivar W05 protein sequences'
+RUN mkblastdb Glycine_soja/PI483463.gnm1.ann1.3Q3Q/glyso.PI483463.gnm1.ann1.3Q3Q.transcript.fna.gz nucl 3848 'Glycine soja PI483463 Transcript Sequences'
+RUN mkblastdb Glycine_soja/PI483463.gnm1.ann1.3Q3Q/glyso.PI483463.gnm1.ann1.3Q3Q.protein.faa.gz prot 3848 'Glycine soja PI483463 Protein Sequences'
+RUN mkblastdb Glycine_soja/PI483463.gnm1.YJWS/glyso.PI483463.gnm1.YJWS.genome_main.fna.gz nucl 3848 'Glycine soja PI483463 Genome Sequence'
+RUN mkblastdb Glycine_soja/PI483463.gnm1.ann1.3Q3Q/glyso.PI483463.gnm1.ann1.3Q3Q.cds.fna.gz nucl 3848 'Glycine soja PI483463 Coding Sequence'
